# (a)
print("D is people")
print("P is is blond")
print("Q is is a westerner")
print("Formal statement: For all x in D, if P(x) then Q(x)")

#(b)
print("D is person")
print("P is has black hair")
print("Q is is a westerner")
print("Formal statement: There exists an x in D such that P(x) and Q(x)")

#(c)
print("D is students")
print("P is studies correctly")
print("Q is has high score")
print("Formal statement: For all x in D, if P(x) then Q(x)")

#(d)
print("D is mammals")
print("P is lives in the sea")
print("Q is is a dolphin or a whale")
print("Formal statement: For all x in D, if P(x) then Q(x)")

#(e)
print("D is birds")
print("P is doesn't have wings and can swim")
print("Q is is a penguin")
print("Formal statement: For all x in D, if P(x) then Q(x)")

#(f)
print("D is bird")
print("P is has wings but can't fly")
print("Formal statement: There exists an x in D such that P(x)")
